// <auto-generated />
using System;
using Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    [Migration("20260506040250_FixSaldoCheckConstraint")]
    partial class FixSaldoCheckConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_transaccion", new[] { "correcta", "fallida", "reversada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estados_cuenta", new[] { "activa", "bloqueada", "cerrada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_cuenta", new[] { "ahorros", "corriente" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipos_transacciones", new[] { "deposito", "retiro", "transferencia" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_identidad");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_completo");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique()
                        .HasDatabaseName("IX_Clientes_DocumentoIdentidad");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("balance");

                    b.Property<int>("EstadosCuenta")
                        .HasColumnType("integer")
                        .HasColumnName("estado_cuenta");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_cuenta");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("RowVersion");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("IX_Cuentas_IdCliente");

                    b.HasIndex("NumeroCuenta")
                        .IsUnique()
                        .HasDatabaseName("IX_Cuentas_NumeroCuenta");

                    b.ToTable("cuenta", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cuentas_Saldo_NoNegativo", "balance >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Entidades.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("EstadoTransaccion")
                        .HasColumnType("integer")
                        .HasColumnName("estado_transaccion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("IdCuentaDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_destino");

                    b.Property<Guid>("IdCuentaOrigen")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_origen");

                    b.Property<decimal>("Monto")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia");

                    b.Property<int>("TipoTransaccion")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_transaccion");

                    b.HasKey("Id");

                    b.HasIndex("Referencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Transacciones_Referencia");

                    b.HasIndex("IdCuentaOrigen", "Fecha")
                        .HasDatabaseName("IX_Transacciones_IdCuentaOrigen_Fecha");

                    b.ToTable("transacciones", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Cuenta", b =>
                {
                    b.HasOne("Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cuentas_Clientes");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entidades.Transaccion", b =>
                {
                    b.HasOne("Domain.Entidades.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuentaOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transacciones_Cuentas");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Domain.Entidades.Cliente", b =>
                {
                    b.Navigation("Cuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
